services:
  sentry-telegram-webhook:
    container_name: sentry-telegram-webhook
    build:
      context: .
      dockerfile: Dockerfile
    image: sentry-telegram-webhook:latest
    env_file:
      - path: .env.example
        required: true
      - path: .env
        required: false
    ports:
      - "${DOCKER_HTTP_IP:-127.0.0.1}:${DOCKER_HTTP_PORT:-6500}:${DOCKER_HTTP_PORT:-6500}"
    restart: unless-stopped
